### ISSUE TITLE
Error with taxios-generate command: Token "components" does not exist. MissingPointerError: Token "components" does not exist.

### ISSUE THREAD

**Issue by TeodorDre** [simplesmiler/taxios#29] opened 2022-08-22 07:56 UTC
taxios-generate v0.2.12

@simplesmiler Denis, hello! i'm using you library for generating types&interfaces from OpenAPI Swagger v3.0.3.
But some things goes wrong, and i don't know what to do. 

Steps for reproduce:

1) `.yaml file` [](https://gist.github.com/TeodorDre/22c9cb23f9537561cb1a8bb156303840)
2) run `taxios-generate -o ./types.ts -e LibX ./swagger.yaml  --skip-validation`, it falls with an exception:

`Token "components" does not exist. MissingPointerError: Token "components" does not exist.` 

But as we can see, this field exist in `.yaml` file. I try to debug it with changing source code, with no success. Could you please help with it? Maybe it is because of OpenAPI version?

**Comment by TeodorDre** [comment] 2022-08-22 07:56
Ask whatever you want, and thanks for your attention here!

**Comment by crutch12** [comment] 2022-08-22 09:57
I think `3.0.3` is not supported (just like `3.1.0`)

https://github.com/simplesmiler/taxios/issues/18

**Comment by simplesmiler** [comment] 2022-08-29 19:59
Hi!

I don't think OpenAPI version has anything to do with your issue.

Judging by the error message, there is an invalid `$ref` somewhere in your file. Correct ref should look something like:

`$ref: '#/components/schemas/<ComponentName>'`

Also strange is the fact that you see this error while running with `--skip-validation`, because I can only trigger it locally when running without it. Are you sure you are running with this flag?

It would really help if you could provide a sample file.

Here is a sample file that uses correct refs format:

<details>
  <summary>api.yaml</summary>

```yaml
openapi: 3.0.3
info:
  title: Test refs
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/users:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
      required:
        - name
      additionalProperties: false
```
</details>

**Comment by simplesmiler** [comment] 2023-01-05 11:17
Closing this under assumption that the source yaml was broken.

@TeodorDre, feel free to reopen if you can provide a sample yaml that reproduces the problem.

**Closed by simplesmiler** 2023-01-05 11:17 UTC
